## Linear Algebra

In [20]:
import numpy as np

In [24]:
A = np.array([
    [2,-1],
    [0,3]
])

B = np.array([
    [1,2],
    [-3,4]
])

### Addition

In [27]:
print(f" Matrix A + B is\n{A+B}")

 Matrix A + B is
[[ 3  1]
 [-3  7]]


### Multiplication

In [31]:
# dot product
print("Dot product using 'np.dot' --->\n",np.dot(A,B)) 

print("Dot product using '.dot' --->\n",A.dot(B))

print("Dot product using '@' --->\n",A @ B)
print((A @ B).shape) 


Dot product using 'np.dot' --->
 [[ 5  0]
 [-9 12]]
Dot product using '.dot' --->
 [[ 5  0]
 [-9 12]]
Dot product using '@' --->
 [[ 5  0]
 [-9 12]]
(2, 2)


In [32]:
print("3A - 2B =\n", 3*A - 2*B)

3A - 2B =
 [[ 4 -7]
 [ 6  1]]


## Determinant and Inverse

In [35]:
import numpy.linalg as LA

determinant = LA.det(A)
print(" |A| = ",determinant)

 |A| =  6.0


#### Invertible

In [38]:
if determinant != 0:
    print(LA.inv(A))
else:
    print("Matrix is not invertible")

[[0.5        0.16666667]
 [0.         0.33333333]]


## Eigenvalues and Eigenvectors  

In [56]:
print("A =\n", A)
eigenvalues , eigenvectors = np.linalg.eig(A)
print("\n Eigen value 1 is:",eigenvalues[0])
print(" and Eigen vector corresponding is:",eigenvectors[:, 0])
print("\n Eigen value 2 is:",eigenvalues[1])
print(" and Eigen vector corresponding is:",eigenvectors[:, 1])


A =
 [[ 2 -1]
 [ 0  3]]

 Eigen value 1 is: 2.0
 and Eigen vector corresponding is: [1. 0.]

 Eigen value 2 is: 3.0
 and Eigen vector corresponding is: [-0.70710678  0.70710678]
