## Linear Algebra

In [1]:
import numpy as np

In [2]:
A = np.array([
    [2,-1],
    [0,3]
])

B = np.array([
    [1,2],
    [-3,4]
])

### Addition

In [3]:
print(f" Matrix A + B is\n{A+B}")

 Matrix A + B is
[[ 3  1]
 [-3  7]]


### Multiplication

In [4]:
# dot product
print("Dot product using 'np.dot' --->\n",np.dot(A,B)) 

print("Dot product using '.dot' --->\n",A.dot(B))

print("Dot product using '@' --->\n",A @ B)
print((A @ B).shape) 


Dot product using 'np.dot' --->
 [[ 5  0]
 [-9 12]]
Dot product using '.dot' --->
 [[ 5  0]
 [-9 12]]
Dot product using '@' --->
 [[ 5  0]
 [-9 12]]
(2, 2)


In [5]:
print("3A - 2B =\n", 3*A - 2*B)

3A - 2B =
 [[ 4 -7]
 [ 6  1]]


## Determinant and Inverse

In [16]:
import numpy.linalg as LA

determinant = LA.det(A)
print(" |A| = ",determinant)

 |A| =  6.0


#### Invertible

In [7]:
if determinant != 0:
    print(LA.inv(A))
else:
    print("Matrix is not invertible")

[[0.5        0.16666667]
 [0.         0.33333333]]


## Eigenvalues and Eigenvectors  

In [8]:
print("A =\n", A)
eigenvalues , eigenvectors = np.linalg.eig(A)
print("\n Eigen value 1 is:",eigenvalues[0])
print(" and Eigen vector corresponding is:",eigenvectors[:, 0])
print("\n Eigen value 2 is:",eigenvalues[1])
print(" and Eigen vector corresponding is:",eigenvectors[:, 1])


A =
 [[ 2 -1]
 [ 0  3]]

 Eigen value 1 is: 2.0
 and Eigen vector corresponding is: [1. 0.]

 Eigen value 2 is: 3.0
 and Eigen vector corresponding is: [-0.70710678  0.70710678]


### Prediction


In [ ]:
X = np.array([[4,1.5,100],
              [6,2.0,150]])
y = np.array([[20],
              [30]])
beta = LA.pinv(X) @ y # here normal formula [β=(X.T * X)^−1  X.T y] doesnot work because 
                      #in this case (X.T * X)^−1 doesnot exist as the determinant is 0 so pseudo inverse gives the best possible solution
                    
X3 = np.array([[8,3,200]])
price3 = X3 @ beta
print(price3)

[[40.]]


### In the above example we find the price of a third car with its given feature by looking the trend of data.